### ISSUE TITLE
PSReadLine integration: history fuzzy search

### ISSUE THREAD

**Issue by vors** [kelleyma49/PSFzf#1]
Awesome project!

I was trying to implement this scenario with `fzf` and PSReadLine, but didn't succeed.
It would be useful to pipe all history records from PSReadLine to `fzf`.
Maybe you know how to get it done?

**Comment by kelleyma49** [comment]
Thanks, I'm glad you like it!

I'm not sure what you're trying to accomplish.  There's `Invoke-FuzzyHistory`(https://github.com/kelleyma49/PSFzf/blob/master/PSFzf.Functions.ps1#L67) that allows you to search through previous history.  Is this what you mean by PSReadLine history records?

**Comment by vors** [comment]
PSReadLine comes with a built-in shortcut for reverse search `Ctrl+R`.
I'd like to start using hisotry piped in `fzf` instead, just like in bash with fzf https://github.com/junegunn/fzf/blob/a71c47140575b324afeb054a4fbc0e3fa505d4d0/shell/key-bindings.bash#L85

It requires to create a PSReadLine binding for `Invoke-FzfHistory`

**Comment by vors** [comment]
Hm, nevermind

It's just `Set-PSReadlineKeyHandler -ScriptBlock { Invoke-FuzzyHistory } -Chord "Ctrl+Y"`

**Comment by vors** [comment]
I'd love to see `key-binding.ps1` and `completion.ps1` in https://github.com/junegunn/fzf/tree/master/shell :)

**Comment by vors** [comment]
* Actually `Get-History`doesn't preserve history across the sessions. PSReadLine implements it's own history preservation mechanics, so `Invoke-FuzzyHistory` cannot be used as-is.
* To match reverse-search behavior, the history item should be inserted to the command line, not invoked. This is very useful, because somebody may want to re-use some part of a long one-liner they wrote a long time ago, but not the whole thing. If we can achieve this behavior with some PSReadLine input buffer manipulations, that would be fantastic and probably would worth to contribute to the main `fzf` project.

**Comment by kelleyma49** [comment]
Try this and let me know if this works for you: #3

**Comment by vors** [comment]
Yes! That's perfect :) 👍

**Comment by kelleyma49** [comment]
Resolved by PR #3
