### ISSUE TITLE
2.3.7-alpha : An exception occurred in custom key handler, see $error for more information: Could not find a part of the path 'C:\github\shit.txt'.

### ISSUE THREAD

**Issue by belotn** [kelleyma49/PSFzf#123]
Hello,

I ran into this message trying 2.3.7-alpha :
An exception occurred in custom key handler, see $error for more information: Could not find a part of the path 'C:\github\shit.txt'.

**Comment by kelleyma49** [comment]
Doh! 😳

Sorry about that. I have fixed it and it will be available in https://www.powershellgallery.com/packages/PSFzf/2.3.8-alpha

**Comment by belotn** [comment]
You're welcome. It made my day :)
