### ISSUE TITLE
Chord does not work on VIMode Command

### ISSUE THREAD

**Issue by belotn** [kelleyma49/PSFzf#133]
All defined chord with Set-PSFzfOption do not work when in vimode "Command". Maybe that's by design ?

**Comment by kelleyma49** [comment]
Can you list recreation steps?

**Comment by bedware** [comment]
I stumbled upon that issue too. I created a small PR to fix that. 

If you are aware of how you can test that you can do these few steps:
* Run in pwsh: Set-PSReadLineOption -EditMode Vi
* Press Escape
* Try any fzf bounded command

**Comment by bedware** [comment]
@belotn hello 👋 Could you review the changes, please?

**Comment by kelleyma49** [comment]
@bedware , not sure if you saw that @belotn 's PR is merged? Are you still having issues?

**Comment by bedware** [comment]
@kelleyma49, you confused me and @belotn. I created the PR and ofc I tested my changes. It works. I just want to close the issue and asked the topic starter to test it and give feedback to get enough arguments to close the issue.

**Comment by kelleyma49** [comment]
My apologies for the confusion!

**Comment by bedware** [comment]
It looks like @belotn is not eager to check the fix. I think you can close it. At least I've checked it. After all, the goal is to make them less, not more.

**Comment by belotn** [comment]
Sorry for the delay. I close the case.
