### ISSUE TITLE
Cannot exchange keys(Ctrl+t Alt+c) for two functions

### ISSUE THREAD

**Issue by 10ve** [kelleyma49/PSFzf#140]
Set-PsFzfOption  -PSReadlineChordSetLocation 'Ctrl+t’-PSReadlineChordProvider 'Alt+c'

only the last works

```
>get-PSReadLineKeyHandler


Key    Function                   Description
---    --------                   -----------
Tab    CustomAction               User defined action
Alt+c  Fzf Provider Select        Run fzf for current provider based on current token
Ctrl+r Fzf Reverse History Select Run fzf to search through PSReadline history
```
it seems that an error occurred when SetPsReadlineShortcut

**Comment by kelleyma49** [comment]
Looks like you're missing a space between `'Ctrl+t'` and `-PSReadlineChordProvider`

**Comment by 10ve** [comment]
> Looks like you're missing a space between `'Ctrl+t'` and `-PSReadlineChordProvider`

 `Set-PsFzfOption  -PSReadlineChordSetLocation 'Ctrl+t’ -PSReadlineChordProvider 'Alt+c'` only the last(alt+c) effect  
![image](https://user-images.githubusercontent.com/11514850/202492159-98b1cd05-ac25-4c9d-becc-7257caa57129.png)
![image](https://user-images.githubusercontent.com/11514850/202492225-67a1c1f9-33d5-4c9b-ab66-176f9b036282.png)

`Set-PsFzfOption -PSReadlineChordProvider 'Alt+c' -PSReadlineChordSetLocation 'Ctrl+t’ ` only the last(ctrl+t) effect  
![image](https://user-images.githubusercontent.com/11514850/202492642-31878620-7d38-4e53-a5fd-30e749643c35.png)
![image](https://user-images.githubusercontent.com/11514850/202492699-92ef0177-352f-4197-8300-9c5b5420e8fb.png)
