### ISSUE TITLE
Continuous tab completion does not work

### ISSUE THREAD

**Issue by pitkali** [kelleyma49/PSFzf#142]
# Steps
1. Enable Tab completion using PSFzf.
2. Type cd and use Tab to start tab completion.
3. Try to confirm one level of completion with directory separator.
# Expected
The directory selected with separator is added to the path and completion continues inside it.
# Actual
The directory separator replaces the entire part of the input being completed.
# Notes
This happens on Powershell 7. It is a regression from #85. The problem is that after [4a60f0e](https://github.com/kelleyma49/PSFzf/commit/4a60f0ebdfc1a9879f809bb4475e62a63d76ae20) continuous completion is decided upon the second item in the array, but fzf is supposed to return expected keys, if any, *before* the completion result. I had to patch it with [5df5fb3](https://github.com/pitkali/PSFzf/commit/5df5fb316ace1fd2d33388453d5ff7b500b5608c) to get it to work again reliably but I don't know at this point if fzf suffers from similar ordering issue with regard to this under Powershell 5.

**Comment by DanSM-5** [comment]
I'm having the same issue with PowerShell 7.3
