### ISSUE TITLE
Prevent the module from creating certain aliases

### ISSUE THREAD

**Issue by dstcruz** [kelleyma49/PSFzf#15]
Is there a way to prevent the module from importing certain aliases? In my case, specifically, the alias `fd` shadows the `fd` command (the cool find command).

Is the solution to do something like this? This doesn't seem very clean, as it might end up not removing the alias that was intended.

```
Import-Module PSFzf -ArgumentList 'Ctrl+T','Ctrl+R'
Remove-Item alias:fd
```

**Comment by glucas** [comment]
+1, using New-Alias to avoid clobbering existing aliases would be good.

**Comment by kelleyma49** [comment]
> Using New-Alias to avoid clobbering existing aliases would be good. but won't solve the issue here where `fd` is an executable on the path rather than a predefined alias.
> 
> I think you'd need to check using Get-Command, e.g.
> 
> ```
> (Get-Command fd -ErrorAction SilentlyContinue)  # fd exists, don't clobber it
> ```

Good point. I've updated PSFzf to use Get-Command. See release https://www.powershellgallery.com/packages/PSFzf/1.1.19.
