### ISSUE TITLE
chords cause powershell to crash

### ISSUE THREAD

**Issue by mattiamarchesini** [kelleyma49/PSFzf#155]
Just installed. I've noticed that sometimes chords like `ctrl+t` or `alt+c` cause the PowerShell window to crush and close itself.

I suspect it has something to do with the size of the list being displayed but I've got no way to be sure

Windows version: 10.0.19044 Build 19044
Powershell version: PowerShell Core 7.2.4
fzf.exe version: 0.30.0 (2093667)

**Comment by kelleyma49** [comment]
Can you share any other information about your environment? 

Try running `$error.clear()`, then one of commands that causes it to crash, then share the contents of `$error`.

I can run <kbd>CTRL+T</kbd> from the root of my C: drive and it will index 1.3 million files without any issues.
