### ISSUE TITLE
How to use Invoke-PsFzfGitBranches

### ISSUE THREAD

**Issue by linw789** [kelleyma49/PSFzf#156]
It seems that `Invoke-PsFzfGitBranches` isn't registed as a cmdlet. Is there way to make it work as `Invoke-FuzzyGitStatus` and set an alias to it?

**Comment by kelleyma49** [comment]
@linw789  , please try the 2.5.2 prelease version and let me know if that fixes your issue

https://www.powershellgallery.com/packages/PSFzf/2.5.2-alpha

**Comment by linw789** [comment]
Thank you for making the change! I will test it later.

**Comment by linw789** [comment]
Hi @kelleyma49 could you also add an alias for branch selection, similar to [this](https://github.com/kelleyma49/PSFzf/blob/master/PSFzf.Functions.ps1#L391)?
