### ISSUE TITLE
Git preview failed when set-location use System.IO.DirectoryInfo Object

### ISSUE THREAD

**Issue by belotn** [kelleyma49/PSFzf#162]
Hi

That's a weird one.... When using a Get-Item to Set-Location, powershell pwd is not "correct" and then Invoke-FuzzyGitStatus preview failed...

![image](https://user-images.githubusercontent.com/3379936/180495364-5ca0314b-c603-4afe-b50e-422f5831da31.png)

using a string with set-location is ok

![image](https://user-images.githubusercontent.com/3379936/180496155-868a32bb-ce2a-43ef-b7e5-761ff91832d1.png)

the better way to resolve the issue is to ask ms to correct powershell... The fastest is to change line in function Invoke-PsFzfGitFiles

    `$previewCmd = "${script:bashPath} \""" + $(Join-Path $PsScriptRoot 'helpers/PsFzfGitFiles-Preview.sh') + "\"" {-1}" + $(Get-ColorAlways) + " \""$pwd\"""`

to

`$previewCmd = "${script:bashPath} \""" + $(Join-Path $PsScriptRoot 'helpers/PsFzfGitFiles-Preview.sh') + "\"" {-1}" + $(Get-ColorAlways) + " \""$($pwd.ProviderPath)\"""`

**Comment by kelleyma49** [comment]
@belotn , please try the 2.5.2 prelease and let me know if that fixes your issue 

https://www.powershellgallery.com/packages/PSFzf/2.5.2-alpha

**Comment by belotn** [comment]
@kelleyma49 It's ok. Works as expected :)
