### ISSUE TITLE
FuzzyGitStatus causes git bash to open

### ISSUE THREAD

**Issue by gmkado** [kelleyma49/PSFzf#163]
I may have something configured incorrectly so please let me know what other info I should provide.  

When I cd into my git repo and use `Invoke-FuzzyGitStatus`, I can see an fzf list of modified files, but navigating the cursor up and down shows nothing in the preview pane.  Instead, an instance of git bash keeps opening and closing immediately.  It looks like it briefly displays a preview in the bash instance before closing.

Am I missing a setting or third party application?  Thanks!

**Comment by gmkado** [comment]
I think I've tracked it down to [this line](https://github.com/kelleyma49/PSFzf/blob/master/PSFzf.Git.ps1#L81), which opens git bash to run the shell script

**Comment by kelleyma49** [comment]
@gmkado , please try the 2.5.2 prerelease and let me know if it fixes your issue 

https://www.powershellgallery.com/packages/PSFzf/2.5.2-alpha

**Comment by gmkado** [comment]
Thanks @kelleyma49 for the response!  I tried v2.5.2 and it still opens bash briefly in a separate window, and the preview pane is blank.

**Comment by kelleyma49** [comment]
What shell are you taking to launch psfzf?

**Comment by gmkado** [comment]
Nevermind I just had to relaunch my powershell, now it works!
