### ISSUE TITLE
fzf does not use FZF_CTRL_T_COMMAND and FZF_ALT_C_COMMAND variables

### ISSUE THREAD

**Issue by vkrol** [kelleyma49/PSFzf#18]
Hello!

fzf does not use FZF_CTRL_T_COMMAND and FZF_ALT_C_COMMAND variables (https://github.com/junegunn/fzf#key-bindings-for-command-line). I think that this is a bug. How can I help with this problem?

Thanks!

**Comment by kelleyma49** [comment]
Thanks for the issue submission.

Indeed, PsFzf doesn't respect those environment variables. I'm in the process of fixing this, beginning with https://github.com/kelleyma49/PSFzf/commit/3cdf116f77893b64eb6d52f087acc2829cceefc5.

**Comment by vkrol** [comment]
@kelleyma49 awesome! Thanks.

**Comment by kelleyma49** [comment]
Available in https://www.powershellgallery.com/packages/PSFzf/1.1.16.
