### ISSUE TITLE
EnableAliasFuzzyZLocation preview window cuts off long paths

### ISSUE THREAD

**Issue by gmkado** [kelleyma49/PSFzf#185]
Is there a way to configure the preview window?  I have `Set-PsFzfOption -EnableAliasFuzzyZLocation` and when I use z.sh to navigate I get this layout:
![image](https://user-images.githubusercontent.com/6592135/188198419-e65e92f7-269a-46a2-8c14-2919e396e07c.png)

Where the preview on the right cuts off the full path

**Comment by kelleyma49** [comment]
@gmkado , try https://www.powershellgallery.com/packages/PSFzf/2.5.11 to see if that works better.
