### ISSUE TITLE
Is there a way to respect .gitignore?

### ISSUE THREAD

**Issue by jan11011977** [kelleyma49/PSFzf#19]
I know there is a way to make fzf respect .gitignore files on Bash, but is there a way to do it with PowerShell? I am struggling to figure it out.

**Comment by kelleyma49** [comment]
There currently isn't a way, but I'll try to put something together this weekend. My thought is to respect `FZF_DEFAULT_COMMAND`, and then you can use ripgrep or your favorite grep tool.

**Comment by kelleyma49** [comment]
The latest release supports `FZF_DEFAULT_COMMAND`. You can use ripgrep or something else that respects .gitignore.

**Comment by Kurren123** [comment]
No one thanked you for this @kelleyma49, so thank you, this was very useful for me
