### ISSUE TITLE
Bind keybind to Invoke-FuzzyEdit doesn't work

### ISSUE THREAD

**Issue by vunhatchuong123** [kelleyma49/PSFzf#196]
With my Editor being nvim. I can type `Invoke-FuzzyEdit` and it works as expected.

But when I excute `Ctrl+d` with 

```pwsh
Set-PSReadlineKeyHandler -Chord 'Ctrl+d' -ScriptBlock {Invoke-FuzzyEdit}
```
My Terminal hang and I have to reopen it.

**Comment by kelleyma49** [comment]
Resolved with #199. Prerelease with this change is here: https://github.com/kelleyma49/PSFzf/releases/tag/v2.5.15
