### ISSUE TITLE
Ctrl-a does not show all branches in Invoke-PsFzfGitBranches

### ISSUE THREAD

**Issue by pluma9** [kelleyma49/PSFzf#207]
Nothing changes after I press Ctrl-a. I ran powershell with NoProfile option to make sure my powershell profile does not cause the problem.

Versions:
fzf 0.35.1
PSFzf 2.5.14

**Comment by kelleyma49** [comment]
Whoops! I added the help text but I forgot to actually implement CTRL+A. 

FIxed in #209
