### ISSUE TITLE
FZF_DEFAULT_COMMAND ignored

### ISSUE THREAD

**Issue by thorstenkampe** [kelleyma49/PSFzf#21]
[latest PSFzf and PowerShell 6.2.0-preview.2 on Windows]

I suspected because of similar timings for different `FZF_DEFAULT_COMMAND` that PSFzf ignores that environment variable. This seems to confirm the problem:
```
pwsh> $Env:FZF_DEFAULT_COMMAND = 'does_not_exist'
pwsh> fzf
>   < [$FZF_DEFAULT_COMMAND failed]

pwsh> Invoke-FuzzySetLocation
>   < 2299/2299
```

**Comment by kelleyma49** [comment]
Thanks for reporting. `Invoke-FuzzySetLocation` should respect `FZF_DEFAULT_COMMAND` if it's set.

Try https://www.powershellgallery.com/packages/PSFzf/1.1.20 to see if your problem is resolved.
