### ISSUE TITLE
Deduplicate history before going through fzf.

### ISSUE THREAD

**Issue by omittones** [kelleyma49/PSFzf#219]
History will usually have a lot of duplicated command executions. My history for example has 18000 entries, most of which repeat. It might be faster to deduplicate history items before passing it to fzf.

Example with lots of repeated lines:
![image](https://user-images.githubusercontent.com/1233302/227257400-1fdc15e0-4709-4df5-b522-604ba17e899c.png)

**Comment by ManuelAF** [comment]
You can tell ReadLine not to store duplicates with
Set-PSReadLineOption -HistoryNoDuplicates

**Comment by omittones** [comment]
@ManuelAF Based on documentation ([link](https://learn.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.4#-historynoduplicates)), quote:

> This option controls the recall behavior. Duplicate commands are still added to the history file. When this option is set, only
> the most recent invocation appears when recalling commands. Repeated commands are added to history to preserve ordering during recall. However, you typically don't want to see the command multiple times when recalling or searching the history.
> 
> By default, the HistoryNoDuplicates property of the global PSConsoleReadLineOptions object is set to True

My setting **IS** set to True, but duplicates are still stored in the history file. My understanding is that this option only controls recall behavior via the terminal so entries won't be deduplicated even when using `Get-History` command, as seen in:

![image](https://github.com/kelleyma49/PSFzf/assets/1233302/ba582478-5a7a-4e9e-9aad-95c2e2405dcf)

So in my case when searching "dir", without deduplication there would be many useless "dir" entries.
