### ISSUE TITLE
Warning about argumentlist even when provided

### ISSUE THREAD

**Issue by glucas** [kelleyma49/PSFzf#22]
As of (I believe)  1.1.19, I get this warning even though I am using -ArgumentList:

    λ Import-Module PSFzf -ArgumentList 'Alt+T','Ctrl+R'
    WARNING: PSReadline chord ctrl+r already in use - keyboard handler not installed.  To bind your own keyboard chord, use  the -ArgumentList parameter when you call Import-Module.
    WARNING: PSReadline chord alt+c already in use - keyboard handler not installed.  To bind your own keyboard chord, use
    the -ArgumentList parameter when you call Import-Module.
    WARNING: PSReadline chord alt+a already in use - keyboard handler not installed.  To bind your own keyboard chord, use
    the -ArgumentList parameter when you call Import-Module.

Despite the warning, the key chord bindings work as expected.

**Comment by kelleyma49** [comment]
Thanks for reporting. I have recreated the issue and submitted a fix.

Try https://www.powershellgallery.com/packages/PSFzf/1.1.20 to verify I've fixed the problem.

**Comment by glucas** [comment]
Looks good - thanks!
