### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by AndreM222** [kelleyma49/PSFzf#223]
Hi, Currently I am using the dracula theme for my terminal on windows and wanted to know if it was possible to change the colors to match

**Comment by kelleyma49** [comment]
I haven't tried it before, but I think you can customize fzf's color scheme by following these instructions: https://github.com/junegunn/fzf/blob/master/ADVANCED.md#color-themes

**Comment by AndreM222** [comment]
this seems to be using bash not powershell
