### ISSUE TITLE
Feature Request: Make commands for git tab expansion configurable

### ISSUE THREAD

**Issue by r3Fuze** [kelleyma49/PSFzf#231]
By default the git tab expansion only works for [`git, tgit, and gitk`](https://github.com/kelleyma49/PSFzf/blob/master/PSFzf.TabExpansion.ps1#L84).

I have `git` aliased to `g` which means I can't use the tab expansion unless I type out the full `git` command.

It would be nice if the list of commands that can trigger the expansion was configurable with for example an environmental variable.

**Comment by kelleyma49** [comment]
This feature request has been released in [2.5.19](https://www.powershellgallery.com/packages/PSFzf/2.5.19)
