### ISSUE TITLE
`Ctrl+t` with command-line content not working as expected.

### ISSUE THREAD

**Issue by segln** [kelleyma49/PSFzf#236]
### Problem
`Ctrl+t` with command-line content not working as expected.

#### Example
Here is a directory on command-line.
![image](https://github.com/kelleyma49/PSFzf/assets/18192378/5bd4e56d-4751-4303-a4d0-310aefb49c0b)

With pressing `Ctrl+t`, PSFzf shows `Appdata`'s entries.
![image](https://github.com/kelleyma49/PSFzf/assets/18192378/bd7bed79-3601-4df2-bfd5-ac410d980200)

But when submit, PSFzf removes `AppData`.
![image](https://github.com/kelleyma49/PSFzf/assets/18192378/b85ad058-d8a9-405b-921a-77c8f3dfd6f1)

### Expected behavior
PsFzf completes entry using the inputted directory.
![image](https://github.com/kelleyma49/PSFzf/assets/18192378/dc33bbf0-802a-4f24-ae87-a603affbcf63)

### Others
I'm not using any custom settings, just `Set-PsFzfOption -TabExpansion`.

**Comment by kelleyma49** [comment]
I can recreate this issue. I'll take a look and see what I can do to fix it

**Comment by kelleyma49** [comment]
Fix is in https://www.powershellgallery.com/packages/PSFzf/2.5.20-alpha
