### ISSUE TITLE
Chronological order in history search

### ISSUE THREAD

**Issue by fungiboletus** [kelleyma49/PSFzf#24]
How to get the chronological order in the history search ? The fzf documentation says : «If you want to see the commands in chronological order, press CTRL-R again which toggles sorting by relevance», but it doesn't look like it's possible with PSFzf.

**Comment by kelleyma49** [comment]
CTRL+R will now control sort order in the latest version (https://www.powershellgallery.com/packages/PSFzf/1.1.23).

**Comment by fungiboletus** [comment]
Thanks !
