### ISSUE TITLE
Why no-sort is default?

### ISSUE THREAD

**Issue by jeiea** [kelleyma49/PSFzf#240]
## Background

I've observed that the expected behavior described below has been absent for quite some time, and I'm eager to understand the reason behind it.

## Steps to reproduce

1. Set up this project and configure it as follows.
```powershell
Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t' -PSReadlineChordReverseHistory 'Ctrl+r'
```

2. Press <kbd>Ctrl+R</kbd> and type `ls -r` in powershell.

## Expected behavior
The results should mimic the oh-my-zsh fzf integration, where entries containing `ls -r` appear first.

<img width="600" alt="image" src="https://github.com/kelleyma49/PSFzf/assets/4188984/5c1c04da-f95a-45f4-b654-894f04d7ea5c">

## Actual behavior
Currently, the most recent item always appears first.

<img width="600" alt="image" src="https://github.com/kelleyma49/PSFzf/assets/4188984/d8a2059b-9e39-4202-8f32-3e9de3304c8e">

**Comment by Navidda** [comment]
I have the same issue, is there any workaround this?
