### ISSUE TITLE
Ctrl+T search doesn't give directories as a result, only files

### ISSUE THREAD

**Issue by DavidColson** [kelleyma49/PSFzf#245]
Using this with Powershell 7.4.1 (Windows 10), when I press Ctrl+T and type, the only results I get are for files, never directories, which makes it difficult to use this for commands where I don't want files. 

I have searched around but have not figured out what I am doing wrong or if this is a bug?

**Comment by DavidColson** [comment]
I don't know if it's feasible, but related to this issue, it would be cool if there was a command for searching directories, and a separate one for searching for files.

**Comment by DavidColson** [comment]
I've seemingly fixed this by installed fd, setting -EnableFd to true _and_ setting the following environment variables:

`FZF_DEFAULT_COMMAND=fd`
`FZF_ALT_C_COMMAND=fd -t d`

However this has broken the colouring of text and I have not been able to fix this. Making `FZF_DEFAULT_COMMAND=fd --color always` just causes the output to be rendered badly.

**Comment by kelleyma49** [comment]
By default, it uses the built-in fzf filesystem walking command as this is the fastest on Windows. Using `FZF_DEFAULT_COMMAND` or passing options through std-in is significantly slower. 

I submitted a PR to add the option to filter directories, but it was rejected by fzf's author: https://github.com/junegunn/fzf/pull/3464.

**Comment by iholston** [comment]
Any update on this? Is there currently any way to include directories in the search without installing fd?

**Comment by kelleyma49** [comment]
Closing this as we now use fzf's built-in walker command. See this commit: 

https://github.com/kelleyma49/PSFzf/pull/268
