### ISSUE TITLE
Setting `EDITOR` does nothing: Can't define any other editor

### ISSUE THREAD

**Issue by redactedscribe** [kelleyma49/PSFzf#246]
Setting `EDITOR` to `$Env:EDITOR = 'codium --goto ":0"'` and running `Invoke-FuzzyEdit` outputs `Executing ''...`.

No matter what `EDITOR` is set to, the output is always blank as shown above.

_Not_ setting `EDITOR` the output is `Executing 'code --goto "C:\{snip}.txt:0"'...` but this is no use to me as I do no use VS Code but _VSCodium_.

Thanks.

PSFzf 2.5.19
fzf 0.46.0
PowerShell v7.4.1

**Comment by kelleyma49** [comment]
I can see in code where it's broken! I will try to fix it in the next couple of days

**Comment by redactedscribe** [comment]
Thanks for the fix @kelleyma49. The variable can now be set. However I have an issue:

**Unset:**

```
Executing 'code --goto "D:\Dev\New Text Document.txt:0"'...
```

**After setting env variables:**

```powershell
$Env:EDITOR = 'codium --goto ":0"'
$Env:PSFZF_EDITOR_OPTIONS = 'test'
```

(`'code --goto ":0"'` was the default before the latest update so I just changed it to `codium`.)

You can see that the file path comes last, unlike when `EDITOR` is _unset_ (above):

```
Executing 'codium --goto ":0" test "D:\Dev\New Text Document.txt"'...`
# Error:
Arguments in `--goto` mode should be in the format of `FILE(:LINE(:CHARACTER))`.
```

I'm not sure how to set `EDITOR` to get the following output (using `PSFZF_EDITOR_OPTIONS` as seen above wouldn't help as it come _before_ the file path):

```
Executing 'codium --goto "D:\Dev\New Text Document.txt:0"'...` 
```

Is there some file path variable for PSFzf that I can use between `--goto` and `":0"`?

Thanks.

**Comment by kelleyma49** [comment]
@redactedscribe , I've added support for detecting codium so you don't have to set editor options. See #248

**Comment by redactedscribe** [comment]
Thanks @kelleyma49! I'll report back if it works for me.
