### ISSUE TITLE
Incorrect Unicode when using CTRL+T

### ISSUE THREAD

**Issue by Flat** [kelleyma49/PSFzf#260]
When using CTRL+T and selecting a file with Japanese characters the returned path is incorrect.

As an example `#Robomeme 😿😱ミャーーー 素材配布 #hololive  #ホロライブ #猫ミーム [q5WTgxw8Trw].webm` becomes `#Robomeme 仭亞繝溘Ε繝ｼ繝ｼ繝ｼ 邏譚宣・蟶・#hololive  #繝帙Ο繝ｩ繧､繝・#迪ｫ繝溘・繝 [q5WTgxw8Trw].webm`

![fzftest](https://github.com/kelleyma49/PSFzf/assets/2048861/7657a44d-90dd-4ffc-a956-05c780c203a0)

**Comment by owenstake** [comment]
The stdin/stdout of fzf is regonized/encoded as utf8, same as all unix tool like ripgrep, fdfind. But the default encoding is unicode(utf16-LE) in the powershell at windows. You may need to set the encoding to utf8 by
```powershell
$InputEncoding = $OutputEncoding =
		[Console]::OutputEncoding = [Console]::InputEncoding =
		[System.Text.Encoding]::utf8
```

**Comment by Flat** [comment]
Looks like that was indeed the issue... Thank you.

**Comment by kivissimo** [comment]
Using `[System.Text.Encoding]::utf8` caused the final output string from fzf to have an extra byte-order mark. Setting the encoding to `New-Object System.Text.UTF8Encoding($False)` instead seemed to fix that issue.
