### ISSUE TITLE
`Invoke-PsFzfRipgrep` throws `unknown action: change-prompt` after updating to 2.6.1

### ISSUE THREAD

**Issue by NikGovorov** [kelleyma49/PSFzf#273]
Environment:
```
PowerShell: v7.4.2
fzf: 0.53.0 (c4a9ccd)
ripgrep 14.1.0 (rev e50df40a19)
```

**Comment by vmotion** [comment]
Change the lines to
`
            --bind "ctrl-f:unbind(change,ctrl-f)+change-prompt( +✅ fzf> )+enable-search+clear-query+rebind(ctrl-r)" `
            --bind "ctrl-r:unbind(ctrl-r)+change-prompt(🔎 ripgrep> )+disable-search+reload($RG_PREFIX {q} || $trueCmd)+rebind(change,ctrl-f)" `
            --prompt '🔎 ripgrep> ' `

`

**Comment by seatrout** [comment]
This fix has not worked for me. Same error occurs.

**Comment by kelleyma49** [comment]
Should be fixed in https://github.com/kelleyma49/PSFzf/releases/tag/v2.6.2
