### ISSUE TITLE
Tab autocomplete deletes argument if not finished with the `Loading...` state.

### ISSUE THREAD

**Issue by SpBills** [kelleyma49/PSFzf#283]
![image](https://github.com/user-attachments/assets/7a4c0daa-0b3f-4068-8357-5bbe41f48a23)

If I hit enter in the following state, it deletes the entire argument. I.E. if I was autocompleting `cd abc/123/` it would replace the entire line with just `cd`.

![image](https://github.com/user-attachments/assets/cca447f2-2887-41ae-86ff-c4bd9d0c049c)

However, once I wait for the following state I can successfully hit enter.

![image](https://github.com/user-attachments/assets/3781d4d4-e1c0-4efe-ad86-bbcf8e684112)

**Comment by kelleyma49** [comment]
Here's the lines from my config file: 

```PowerShell
Import-Module PSFzf
Set-PsFzfOption `
    -TabExpansion `
    -PSReadlineChordProvider 'Ctrl+t' `
    -PSReadlineChordReverseHistory 'Ctrl+r' `
    -PSReadlineChordReverseHistoryArgs 'Alt+a' `
    -EnableAliasFuzzyEdit `
    -EnableAliasFuzzyFasd `
    -EnableAliasFuzzyHistory `
    -EnableAliasFuzzyKillProcess `
    -EnableAliasFuzzySetLocation `
    -EnableAliasFuzzyZLocation `
    -EnableAliasFuzzyGitStatus `
    -EnableAliasFuzzySetEverything `
    -GitKeyBindings #`
    #-EnableFd

Set-PSReadLineKeyHandler -Key Tab -ScriptBlock { Invoke-FzfTabCompletion }
```

**Comment by SpBills** [comment]
@kelleyma49 Hey! I appear to have solved the issue. I was on the default distribution of pwsh 5.1 that comes with windows. I switched to 7.x and we're all good now.
