### ISSUE TITLE
Ctrl + R fzf clears terminal

### ISSUE THREAD

**Issue by alcroito** [kelleyma49/PSFzf#30]
Hi,

If i had some output in my terminal, and then press Ctrl + R, the fzf output appears, and after i select something, the output of the terminal is not restored.

Is there a way to keep the output?

**Comment by wjrogers** [comment]
I have the same problem and concluded it was a problem with fzf itself, which I reported here: https://github.com/junegunn/fzf/issues/1766

**Comment by kelleyma49** [comment]
There's a workaround for this in v1.2.00 (https://www.powershellgallery.com/packages/PSFzf/1.2.0).
