### ISSUE TITLE
Support --expect 

### ISSUE THREAD

**Issue by glucas** [kelleyma49/PSFzf#32]
It looks like --expect works OK on Windows and would be useful to build PowerShell functions that take different actions on the search results. Could it be added to the Invoke-Fzf wrapper?

**Comment by kelleyma49** [comment]
I'm working on this. Having some issues with my github actions - please bear with me. :)

**Comment by kelleyma49** [comment]
Here's a prerelease version with expect support: https://www.powershellgallery.com/packages/PSFzf/1.1.35-alpha.

I haven't had time to test if it really works yet, but feel free to try it out.

**Comment by kelleyma49** [comment]
@glucas, did this work for you?

**Comment by glucas** [comment]
Yes, this works! Sorry, came back to check something else and realized this was still open.
