### ISSUE TITLE
Key chords do not always register when Import-Module is run in $PROFILE

### ISSUE THREAD

**Issue by kalingibbons** [kelleyma49/PSFzf#33]
I'm finding that the module import process is not working from the `$PROFILE` configuration file. On my work computer, I got it to work consistently by moving the import statement from the top of `$PROFILE` to the bottom, but it has not been effective for my laptop. I always have to wait for powershell to load, then run the import statement manually. I assume powershell is loading something asynchronously that is overwriting the chords, but I don't know enough about it to figure out what it could be.

Here's a snippet from my `$PROFILE` with the imports.

```powershell
# Modules
Import-Module PSReadLine
Import-Module PSFzf -ArgumentList 'Ctrl+t', 'Alt+r' -Force
Import-Module Get-ChildItemColor

# Module settings
Set-PSReadLineOption -EditMode Vi
```

Does anyone have a trick to make sure the chords always work?

**Comment by kelleyma49** [comment]
Try using the new command `Set-PsFzfOptions` in the v1.2.00 release:

Release notes: https://github.com/kelleyma49/PSFzf/releases/tag/v1.2.00
Module link: https://www.powershellgallery.com/packages/PSFzf/1.2.0

**Comment by kelleyma49** [comment]
Closing this as I haven't heard a response, so I'm assuming my suggestion worked :)
