### ISSUE TITLE
Prompt string gets erased

### ISSUE THREAD

**Issue by jm33-m0** [kelleyma49/PSFzf#42]
1. Press <kbd>Ctrl-r</kbd>
2. Type something to search
3. Press <kbd>Enter</kbd> to select an entry
4. The entry pops up, with powershell prompt erased

![PSFzf](https://user-images.githubusercontent.com/10167884/77028792-d4a83c80-69d4-11ea-8ecd-9f59637fad3e.png)

**Comment by kelleyma49** [comment]
This was addressed in version 1.2.0 (https://www.powershellgallery.com/packages/PSFzf/1.2.0).

**Comment by jm33-m0** [comment]
Thank you for the fix👍
