### ISSUE TITLE
[GetFullHistory]can be better :) 

### ISSUE THREAD

**Issue by AHPanna** [kelleyma49/PSFzf#47]
https://github.com/kelleyma49/PSFzf/blob/944043fcc907c3ba438ceeacd7c7f746c512cb3b/PSFzf.Functions.ps1#L94

``` $result = Get-Content (Get-PSReadlineOption).HistorySavePath | Invoke-Fzf -Reverse -NoSort```

**Comment by varvir** [comment]
Thanks. This is what i searched. How can I set this by myself?
