### ISSUE TITLE
Is there any way to change the layout?

### ISSUE THREAD

**Issue by ssxwcz** [kelleyma49/PSFzf#48]
I tried setting $env:FZF_DEFAULT_OPTS="--height 40% --layout=reverse", but it seems to be invalid for PSFzf
![2020-05-10](https://user-images.githubusercontent.com/43665491/84240588-d8a9ad80-ab30-11ea-99c1-bac7443bb934.gif)

**Comment by musm** [comment]
Same Q

**Comment by kelleyma49** [comment]
Should be resolved now - try this version: https://www.powershellgallery.com/packages/PSFzf/2.0.2-alpha

**Comment by ssxwcz** [comment]
> Should be resolved now - try this version: https://www.powershellgallery.com/packages/PSFzf/2.0.2-alpha

Thanks, PSFzf can read FZF_DEFAULT_OPTS already.
Also, can I ask if FZF_CTRL_T_OPTS is available under Windows? I didn't find any useful information in fzf, which seems to be invalid after my testing

**Comment by kelleyma49** [comment]
> > Should be resolved now - try this version: https://www.powershellgallery.com/packages/PSFzf/2.0.2-alpha
> 
> Thanks, PSFzf can read **FZF_DEFAULT_OPTS** already.
> Also, can I ask if **FZF_CTRL_T_OPTS** is available under Windows? I didn't find any useful information in fzf, which seems to be invalid after my testing

This was broken as well. I've fixed it and the other FZF_*_OPTS variables. You can try it in this new prerelease version here: https://www.powershellgallery.com/packages/PSFzf/2.0.3-alpha

**Comment by ssxwcz** [comment]
> > > Should be resolved now - try this version: https://www.powershellgallery.com/packages/PSFzf/2.0.2-alpha
> > 
> > 
> > Thanks, PSFzf can read **FZF_DEFAULT_OPTS** already.
> > Also, can I ask if **FZF_CTRL_T_OPTS** is available under Windows? I didn't find any useful information in fzf, which seems to be invalid after my testing
> 
> You're correct - this was broken as well. I've fixed it and the other FZF_*_OPTS variables. You can try it in this new prerelease version here: https://www.powershellgallery.com/packages/PSFzf/2.0.3-alpha

Thank you very much. Everything's fine now.
