### ISSUE TITLE
Text preview with bat is not available after PSFzf version 2.1.0

### ISSUE THREAD

**Issue by ssxwcz** [kelleyma49/PSFzf#65]
After upgrading PSFzf to version 2.1.0, I found that I could not use bat for text preview.
This is my fzf configuration.
```ps1
$env:FZF_DEFAULT_OPTS="--prompt '⯈ ' --height 50% --layout=reverse --border 
--color=dark
--color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f
--color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7"
$env:FD_OPTIONS="--hidden --follow"
$env:FZF_DEFAULT_COMMAND="fd --type f --type l {0}" -f $env:FD_OPTION
$env:FZF_CTRL_T_OPTS='--preview "bat --style=numbers,changes,header --color=always --theme=Dracula --line-range :500 {}  || cat {}"'

```

When in the user directory, it can preview normally.
![1](https://user-images.githubusercontent.com/43665491/104929215-8ee64700-59de-11eb-840f-1479260f742b.gif)

When entering a random directory, I can't use bat to preview, and the system can't find the specified file.
![2](https://user-images.githubusercontent.com/43665491/104929113-724a0f00-59de-11eb-9133-fd0d2cb1b4cb.gif)

**Comment by kelleyma49** [comment]
try https://www.powershellgallery.com/packages/PSFzf/2.2.0

**Comment by ssxwcz** [comment]
> try https://www.powershellgallery.com/packages/PSFzf/2.2.0

Still the same problem, prompting the system can not find the specified path
![image](https://user-images.githubusercontent.com/43665491/105663108-5b3e7c00-5f0c-11eb-8c08-dbdff4ae0c45.png)

**Comment by rashil2000** [comment]
Hi @kelleyma49, still facing the same issue with bat preview in locations other than home directory. My PsFzf version is 2.2.6

**Comment by rashil2000** [comment]
I think the issue is that the preview only seems to work if the full path is shown in the fzf list. This is unique to PsFzf. In bash, relative paths work fine with preview.

**Comment by rashil2000** [comment]
Putting a `Resolve-Path | ` before `Invoke-Fzf` fixes this. 

https://github.com/kelleyma49/PSFzf/blob/b97263a30addd9a2c84a8603382c92e4e6de0eeb/PSFzf.Base.ps1#L529
