### ISSUE TITLE
Tab Expansion Error on different drive

### ISSUE THREAD

**Issue by doongjohn** [kelleyma49/PSFzf#66]
$PROFILE
```powershell
Set-PSReadLineKeyHandler -Key Tab -ScriptBlock { Invoke-FzfTabCompletion }
```

---

`Tab Expansion` on `C drive`

![image](https://user-images.githubusercontent.com/40219740/107131083-04c33b80-6917-11eb-99fc-93360b42c936.png)

`Tab Expansion` on `D drive`

![image](https://user-images.githubusercontent.com/40219740/107131051-b0b85700-6916-11eb-9c52-1238e19d054b.png)

`$error`

![image](https://user-images.githubusercontent.com/40219740/107131128-4bb13100-6917-11eb-8a8f-221624360e41.png)

**Comment by kelleyma49** [comment]
should be fixed in https://www.powershellgallery.com/packages/PSFzf/2.2.2
