### ISSUE TITLE
Invoke-FuzzyEdit doesn't  open the file, if directory is given

### ISSUE THREAD

**Issue by mattia72** [kelleyma49/PSFzf#67]
$env:EDITOR='notepad'
    fe <dir> 

Error: file not found 
The following command shows, that the editor was called with wrong parameter:

    Get-CimInstance Win32_Process -Filter "name='notepad.exe'" | select CommandLine

**Comment by kelleyma49** [comment]
Should be fixed in https://www.powershellgallery.com/packages/PSFzf/2.2.1
