### ISSUE TITLE
Tab-completion preview fails if module loads from path with space

### ISSUE THREAD

**Issue by glucas** [kelleyma49/PSFzf#69]
If you have PsFzf loading from a path that contains spaces (in my case, from a corporate OneDrive directory where My Documents is mapped) then the preview for tab-completion fails. 

I suspect you need to quote the path [here](https://github.com/kelleyma49/PSFzf/blob/d96247d363a5cbbe3b37d97ed3fcff75fce6c4c2/PSFzf.TabExpansion.ps1#L269):
-File $previewScript

**Comment by kelleyma49** [comment]
This should be resolved in https://www.powershellgallery.com/packages/PSFzf/2.2.2
