### ISSUE TITLE
[Feature request] Set the current location as the parent of the user's selection file in fzf

### ISSUE THREAD

**Issue by pluma9** [kelleyma49/PSFzf#72]
I would like to have the ability to fuzzy search a file and have the current working location set to the directory that contains the selected file.

For example, I have a directory structure like this:

├───backend      
│   data.json
│   main.cs  
│                
└───frontend     
│   data.json
│   main.js 
└───...
There are times when I want to go to the **backend** directory to work on a few backend related files and I don't remember the name of the directory, but know the directory contains a file called **main.cs**. It will be helpful if there's a new command or a new parameter added to one of the existing commands that allows me to fuzzy search the **main.cs** file and then set the current working directory to **backend**.

I think this is a common use case that other people may also need.

**Comment by mattcargile** [comment]
You could make a `function`. 

```powershell
function Set-FuzzyParentDirectory { 
Set-Location ( Split-Path ( ( cmd.exe /S /C dir /B /S ) | Invoke-Fzf ) -Parent )
}
```

Then you can combine with a `Get-PSReadlineKeyHandler`.

**Comment by pluma9** [comment]
Thanks for your idea. I've ended up with a slightly different but equivalent function:
```powershell
function Set-FuzzyParentDirectory {
  Set-Location -LiteralPath (Split-Path (fzf) -Parent)
}
```

**Comment by mattcargile** [comment]
Glad you got it working! There is also a new feature for `ALT` + `C` where you can have similar behavior as this function. You can replace the function from `Set-Location` to your iteration. I may incorporate it into my workflow.

https://github.com/kelleyma49/PSFzf/issues/88#issuecomment-1025042065
