### ISSUE TITLE
Enabling aliases is very slow

### ISSUE THREAD

**Issue by srid** [kelleyma49/PSFzf#73]
I add the following to my PS init script to enable aliases on all shells:

```powershell
echo "Loading aliases ..."
Enable-PsFzfAliases
echo "Done."
```

However this slows down the shell initialization by several seconds (5s). Any way to speed things up here?

**Comment by srid** [comment]
```
> Measure-Command { Enable-PsFzfAliases }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 4
Milliseconds      : 308
Ticks             : 43080303
TotalDays         : 4.98614618055556E-05
TotalHours        : 0.00119667508333333
TotalMinutes      : 0.071800505
TotalSeconds      : 4.3080303
TotalMilliseconds : 4308.0303
```

**Comment by kelleyma49** [comment]
Try using `Set-PsFzfOption`. You need to explicitly specify which aliases you want to enable, but it should speed up load time.

`Enabe-PsFzfAliases` needs to do more checking to prevent clashing with exes in your `%PATH%`.
