### ISSUE TITLE
CTRL-T does not work in vi-mode

### ISSUE THREAD

**Issue by jnunderwood** [kelleyma49/PSFzf#74]
I use vi-mode on the powershell command line by putting this in my profile:

```powershell
Set-PSReadlineOption -EditMode vi
```

When using vi-mode, CTRL-T transposes characters. Is there any way to override the default behavior so that fzf is invoked instead?

**Comment by kelleyma49** [comment]
Apologies for the delayed response!

Make sure that line comes _before_ you load the PSFzf module or before you call `Set-PsFzfOption` in your profile.

**Comment by jnunderwood** [comment]
Thank you!

**Comment by sim590** [comment]
Related to this, I realized that FZF is not called when you're in Normal mode (after pressing ESC) and `ctrl-r` will call the powershell reverse search instead:

![image](https://user-images.githubusercontent.com/4147254/219124641-53b562b4-a28a-430b-8662-7dcfe6cc8d2a.png)

On Windows, I get an input prompt `find:` which is the default reverse search prompt.

Could FZF also register correctly in normal mode ? For now, I really have to be in Insert mode for FZF to work correctly.
