### ISSUE TITLE
Alt-C seems to leave orphaned jobs running in the background

### ISSUE THREAD

**Issue by donovanlange** [kelleyma49/PSFzf#8]
Here's what I see when running `Get-Job`:

![image](https://cloud.githubusercontent.com/assets/9953861/26321771/102626a8-3edd-11e7-8e99-871c45d1f3d5.png)

New jobs seem to be created every time I invoke `Alt-C`.

**Comment by kelleyma49** [comment]
Yikes!  I can recreate this issue.  Let me take a look at my code and see what's going on.  Thanks for the bug report.
