### ISSUE TITLE
Missing partial history search functionality

### ISSUE THREAD

**Issue by kylo252** [kelleyma49/PSFzf#82]
When using `zsh` you can invoke the history widget and it will use what you already have as input to match commands from history. While `PSFzf` doesn't care about what you already have written before invoking it `ctrl+r`.

A second point is that it doesn't replace the entire line but rather insert it at the cursor position. I suspect because you had always planned for this to be used on an empty line.

See an example here:
![lzFJZh4O5l](https://user-images.githubusercontent.com/59826753/119222630-8e2d0100-baf5-11eb-8097-84962809d025.gif)

I tried to take a look at the code but sadly my experience with PowerShell scripting is very limited. I suspect you can probably re-use some of the logic in `PSFzf.TabExpansion.ps1` specifically the part where you use `GetBufferState()`. 

_P.S. thanks for the amazing work!_

**Comment by kelleyma49** [comment]
Good points. I will look at this when I have some free time. It shouldn't be too hard to support.
