### ISSUE TITLE
Arrow keys are unusable when using Windows Terminal

### ISSUE THREAD

**Issue by Namorzyny** [kelleyma49/PSFzf#84]
PSFzf Version: 2.2.6
PowerShell Version: 5.1.19041.906
Windows Version: 10.0.19043.985
Windows Terminal Version: 1.8.1521.0

Can't select items by arrow keys, just output ^[[A... and exit (like pressing Esc). In conhost.exe it works fine.

![Screenshot 2021-06-08 193443](https://user-images.githubusercontent.com/17642329/121178362-008d3780-c891-11eb-9fb7-4ca927292952.png)

**Comment by Namorzyny** [comment]
This issue can't reproduce on my other computer with the same environment but without clink installed (https://chrisant996.github.io/clink/). It seems that clink injection causes this issue.

**Comment by rashil2000** [comment]
I'd like to get this issue reopened.

Clink is really essential, I can't imagine uninstalling it.

Besides, all the keys work fine when history is searched through <kbd>Ctrl</kbd>+<kbd>R</kbd>, so why is <kbd>Ctrl</kbd>+<kbd>T</kbd> for file searching causing a problem?

**Comment by rashil2000** [comment]
A temporary and ugly workaround is to unset `WT_SESSION` environment variable before calling any PSFzf functions:

```pwsh
if (Test-Path Env:WT_SESSION) {
  $tempwt = $Env:WT_SESSION
  $Env:WT_SESSION = ''
}
Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t' -PSReadlineChordReverseHistory 'Ctrl+r'
if ($tempwt) { $Env:WT_SESSION = $tempwt }
```

**Comment by rashil2000** [comment]
I have narrowed down the problem to this line:
https://github.com/kelleyma49/PSFzf/blob/b97263a30addd9a2c84a8603382c92e4e6de0eeb/PSFzf.Base.ps1#L296

Specifying height in any way messes up the keys.

**Comment by kelleyma49** [comment]
Are you starting PowerShell from clink? If I do that I can recreate your issue. My guess it's conflicting with Windows Terminal's VT sequence support (https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences).

**Comment by rashil2000** [comment]
No, I'm starting it from the Windows Terminal profile. 

FWIW, I can recreate this issue even on conhost (by running PowerShell Core directly from the start menu) - by defining an environment variable `$Env:FZF_DEFAULT_OPTS="--height=40%"`.

**Comment by kelleyma49** [comment]
I think I have a work around. It's an issue with a change I made to fzf months ago.

**Comment by rashil2000** [comment]
Oh, okay, thanks for the quick fix!

I apologize if this sounds trivial, but I'm curious to know why this affects only Ctrl+T function and not Ctrl+R function?

**Comment by kelleyma49** [comment]
fzf versions great than 0.27.3 should resolve this problem, so I'm closing this for now. Let me know if you see it again.
