### ISSUE TITLE
Result of TAB completion not written to command line

### ISSUE THREAD

**Issue by f0rdprefect** [kelleyma49/PSFzf#85]
# DO

1. Open Powershell
2. ``Set-PSReadLineKeyHandler -Key Tab -ScriptBlock { Invoke-FzfTabCompletion }``
3. Type something and hit `` <TAB>``
4. fzf opens and I can type to narrow down matches and select the item I want on the command line
5. hit ``<ENTER>`` 

# GET

the text I typed to narrow down the list of results

# EXPECT

the Item I selected appended to my command line

# Remark

Powershell 5.1.17763.1971

Using all other chords like <CTRL> - R work as expected. I guess I am missing something? Anything else I can try?

**Comment by kelleyma49** [comment]
![TabCompleteIssue](https://user-images.githubusercontent.com/2152684/129145854-fa95ba27-9ee0-4528-ac7e-921bd13867ad.gif)

Can you give me more information? I can't see to recreate your issue. See attached gif.

**Comment by f0rdprefect** [comment]
Can do but I am on extender parental leave. It will be not before end of
October...

**Comment by kelleyma49** [comment]
When you get a chance, try running the following before tab completion:

`$error.Clear()`

Try the tab completion, then run the following after and post the output:

`$error`

**Comment by koalp** [comment]
I have the same issue for and there is no `$error`.

What I’ve done : 
``` powershell
$error.Clear()
$error.Cl<tab>  # completion not working
$error # no output
```

**Comment by constantbratu** [comment]
Confirm tab completion not working here also.

**Comment by redcoreit** [comment]
I'm experiencing this issue as well.
`$error` is empty.

```
Name             : ConsoleHost
Version          : 5.1.19041.1151
InstanceId       : 58407a44-9a4c-451d-a21c-338dc8c5723f
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : hu-HU
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.2.9      PSFzf                               {Enable-PsFzfAliases, Invoke-FuzzyEdit, Invoke-FuzzyFasd, Invoke-FuzzyGitStatus...}
Script     2.1.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}
Script     0.7.3      posh-git                            {Add-PoshGitToProfile, Add-SshKey, Enable-GitColors, Expand-GitCommand...}
Script     1.4.3      ZLocation                           {Get-ZLocation, Invoke-ZLocation, Pop-ZLocation, Remove-ZLocation...}
```

**Comment by belotn** [comment]
I have 2 version of powershell here (5.1 and 7.2), the issue appears in 5.1 but not in 7.2.

**Comment by belotn** [comment]
On powershell 5, $script:fzfOuput contains 2 value the selected FZF return and the queried path, on powershell 7 only the result... 

![image](https://user-images.githubusercontent.com/3379936/148680062-73de296a-5d02-4bed-8b32-815c51968217.png)

**Comment by roachsinai** [comment]
Same issue on powershell 5.

**Comment by kelleyma49** [comment]
I see what is happening, but I'm not sure why. 

The order of outputs from fzf is inconsistent in PowerShell 5. fzf is supposed to output the query first, then the selections. It does this in PowerShell 7 just fine, but not in 5.

**Comment by roachsinai** [comment]
@kelleyma49 thanks! It works. But seems it not work with soft link with fuzzyselectdirectory.

**Comment by roachsinai** [comment]
> @kelleyma49 thanks! It works. But seems it not work with soft link with fuzzyselectdirectory. I will open a new issue.

Soft link not work is my fault, sorry for that.
