### ISSUE TITLE
Add option to use something else instead of `Set-Location` with `Invoke-FzfPsReadlineHandlerSetLocation`

### ISSUE THREAD

**Issue by Aankhen** [kelleyma49/PSFzf#88]
This package is awesome! The Alt+C binding is what I’m most interested in. I try to avoid `cd`/`Set-Location`, though; I’d like to be able to use `Push-Location` or even zoxide instead. Would it be possible to add a setting to use a different command? (I tried to do this myself and thought I got it right on the script side, but I couldn’t figure out how to get PowerShell to pick up my changes even after rebuilding and reimporting.)

**Comment by mattcargile** [comment]
I think you want these environment variables?

`$env:FZF_ALT_C_COMMAND`
`$env:FZF_ALT_C_OPTS`

**Comment by mattcargile** [comment]
Also, did you Build the `.sln` as well and copy the `.dll` into the root directory prior to `Import-Module`? You could try adding a `-Verbose` flag to see what the error was. 

The solution also has a dependency on this [add-on](https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017-18561).

**Comment by kelleyma49** [comment]
I added a new option to `Set-PsFzfOption` called `AltCCommand`, which accepts a scriptblock which is used as a replacement for the command in the Alt+C function. Refer to the default scriptblock for an example: 

https://github.com/kelleyma49/PSFzf/blob/626aa365a2c2702516903b4cee050b6cceb03ff0/PSFzf.Base.ps1#L34

**Comment by Aankhen** [comment]
That works perfectly with zoxide. Thank you very much!
