### ISSUE TITLE
Add ability to specify options for fzf

### ISSUE THREAD

**Issue by dejvid-smth** [kelleyma49/PSFzf#89]
First, this is a great tool. I would like to be able to specify command line options that this tool sends to `fzf`.

This can already be set globally by using fzf's env variable `FZF_DEFAULT_OPTS` but that's not what I am looking for. I want to specify default options only for the case when fzf is invoked by PSFzf. Could you add another option or env variable for that ?

For example, zoxide uses another env variable for that - `_ZO_FZF_OPTS`: https://github.com/ajeetdsouza/zoxide#environment-variables

**Comment by kelleyma49** [comment]
I've added the feature and I've published a prerelease version - give it a try! See the readme for the env var name.

https://www.powershellgallery.com/packages/PSFzf/2.3.1-alpha

**Comment by dejvid-smth** [comment]
I have tried it and it looks good. Thank you !
