### ISSUE TITLE
Error when TAB Completion is invoke from network drive or share

### ISSUE THREAD

**Issue by belotn** [kelleyma49/PSFzf#94]
When invoking Tab completion and  CurrentDir ($pwd) is on a network drive or share, $process.Start() fail with error "Directory name is not valid"

psfzf : 2.2.9
Powershell : 5.1

and on powershell 7.2,  the shell freeze.

**Comment by dslgr** [comment]
Ctrl+t, ctrl+r, and alt+c all seem to be broken when on a network share as well. I'm on powershell v7.2.1 and psfzf v2.2.9

**Comment by dslgr** [comment]
To elaborate, psfzf just does nothing in those scenarios. It works when the pwd isn't a network share.

**Comment by belotn** [comment]
One solution is to use $pwd.ProviderPath not $pwd.Path

![image](https://user-images.githubusercontent.com/3379936/147406700-4f1f535c-2b6d-4390-9269-16f5300d345b.png)

**Comment by belotn** [comment]
I confirm that version 2.3.2 correct the issue.
