### ISSUE TITLE
Exception in custom key handler when kubectl completion finds no results

### ISSUE THREAD

**Issue by Aankhen** [kelleyma49/PSFzf#95]
The pre-release versions of kubectl v1.23.0 include PowerShell completion, [which is provided under the hood by spf13/cobra](https://github.com/kubernetes/kubernetes/blob/9a75e7b0fd1b567f774a3373be640e19b33e7ef1/vendor/github.com/spf13/cobra/powershell_completions.go#L20). This works beautifully most of the time in conjunction with `Set-PSReadLineKeyHandler -Key Tab -ScriptBlock { Invoke-FzfTabCompletion }`:

![Pressing Tab retrieves and shows the list of resources to complete](https://user-images.githubusercontent.com/978992/143733650-2ee6d473-3758-4dbb-9bba-a1c5388ecd66.png)

However, there seems to be an issue when there are no completions available:

![Pressing Tab results in an exception message when no completions are available](https://user-images.githubusercontent.com/978992/143733702-ca73f501-cd70-446d-945a-7f2da5668a2b.png)

(Note that pressing <kbd><kbd>Ctrl</kbd> + <kbd>C</kbd></kbd> has no effect. I have to press <kbd>Enter</kbd> to run the command before I can do anything else.)

I’ll reproduce it in text for legibility, though of course without the formatting:
```
❯❯ kubectl get pods fAn exception occurred in custom key handler, see $error for more information: Exception calling "CompleteInput" with "3" argument(s): "Cannot process argument because the value of argument "completionText" is null. Change the value of argument "completionText" to a non-null value."
~
❯❯ kubectl get pods f
Error from server (NotFound): pods "f" not found
~ took 1s157ms
❯❯ kubectl asdasdAn exception occurred in custom key handler, see $error for more information: Exception calling "CompleteInput" with "3" argument(s): "Cannot process argument because the value of argument "completionText" is null. Change the value of argument "completionText" to a non-null value."
~ took 1s157ms
❯❯ kubectl asdasd
E1128 12:56:48.823585   19468 run.go:120] "command failed" err="unknown command \"asdasd\" for \"kubectl\""
```
Now, if I run the command that the application’s completion script runs under the hood, this is what I see:
```
❯❯ k __complete asdasd
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```
Which is the result of [this code](https://github.com/kubernetes/kubernetes/blob/9a75e7b0fd1b567f774a3373be640e19b33e7ef1/vendor/github.com/spf13/cobra/powershell_completions.go#L162-L173):
```
    if (($Directive -band $ShellCompDirectiveNoFileComp) -ne 0 ) {
        __kubectl_debug "ShellCompDirectiveNoFileComp is called"

        if ($Values.Length -eq 0) {
            # Just print an empty string here so the
            # shell does not start to complete paths.
            # We cannot use CompletionResult here because
            # it does not accept an empty string as argument.
            ""
            return
        }
    }
```

As far as I can tell, the completion script is doing the right thing. Without PsFzf, pressing <kbd>Tab</kbd> does nothing if there are no completions, as you’d expect, and lets you continue your input. With PsFzf, pressing <kbd>Tab</kbd> with no completions available causes an error and prevents you from using <kbd><kbd>Ctrl</kbd> + <kbd>C</kbd></kbd> to cancel the input.

I’m running PsFzf v2.3.1-alpha (which I upgraded to from v2.2.9 in case it fixed this bug) with PowerShell v7.2.0 under Windows 10.0.19043 (64-bit).

**Comment by kelleyma49** [comment]
Thank you for the bug report. 

Can you print out the value of `$error`? I'd like to see the stack traceback where `CompleteInput` is being called.

**Comment by Aankhen** [comment]
Sure, here you go:
```
C:\Users\A> k get pod asdasdAn exception occurred in custom key handler, see $error for more information: Exception call
C:\Users\A> $error
MethodInvocationException: Exception calling "CompleteInput" with "3" argument(s): "Cannot process argument because the value of argument
"completionText" is null. Change the value of argument "completionText" to a non-null value."

MethodInvocationException: Exception calling "CompleteInput" with "3" argument(s): "Cannot process argument because the value of argument
"completionText" is null. Change the value of argument "completionText" to a non-null value."
```

**Comment by kelleyma49** [comment]
Apologies it took so long to look at this. 

I can recreate the issue on my local machine. Note that the same error is thrown even if PSFzf isn't used, but it's likely consumed so you don't see it from the command line. I'll try and make PSFzf more robust in cases like this.

**Comment by kelleyma49** [comment]
This change is available in https://www.powershellgallery.com/packages/PSFzf/2.5.4-alpha
